#' Psuedo-quadrat data for GB NVC Comunities
#'
#' @description  A dataset containing pseudo-quadrat data for NVC
#' communities generated by random sampling from NVC species
#' list. The psuedo-quadrat data comes from a study by Tipping \emph{et al.} 2013.
#'
#' @details When generating psudeo-quadrants the  probabilities
#' of species being in a sample were set to match the
#' constancy scores of the species in that given NVC
#' community/sub-community. The probabilities associated
#' with each constancy score were 0.1, 0.3, 0.5, 0.7 and 0.9 for
#' constancy scores 1, 2, 3, 4 and 5 respectively. The number
#' of psuedo-quadrats generated for each NVC community or
#' sub-community was set to match the number of samples originally
#' used to define the NVC and produce the contingency tables.
#'
#' The citation for the paper is:
#' Tipping, E., Henrys, P. A., Maskell, L. C., & Smart, S. M. (2013). Nitrogen deposition effects on plant species diversity; Threshold loads from field data. \emph{Environmental Pollution}, 179, 218-223.
#'
#'
#'
#' @format A data frame with 709695 rows and 6 variables:
#' \describe{
#'   \item{name}{species scientific name}
#'   \item{spp}{species code}
#'   \item{Pid2}{psuedo-quadrat ID}
#'   \item{Pid3}{ID created concatenating NVC and psuedo-quadrat ID `Pid2`}
#'   \item{Pid3}{psued-quadrat number}
#' }
#' @source \url{http://dx.doi.org/10.1016/j.envpol.2013.04.008}
"ps_quad"


#' NVC community floristic tables
#'
#' @description  A dataset of the NVC community floristic table information.
#' For each NVC community/sub community this lists the species present and their
#' respective constancy and frequency values.
#'
#' @details The data in this dataset can be used to generate new psuedo-quadrats
#' for each NVC community/sub community.
#'
#'
#' @format A data frame with 48194 rows and  variables:
#' \describe{
#'   \item{NVC}{The NVC community or sub-community code}
#'   \item{BRC}{species ID code as used historically by the BRC}
#'   \item{Species}{The species/taxa scientific name}
#'   \item{Constancy}{The constancy value for the species specifying how commonly the species are likley to be in
#'   samples from that NVC. Ranges from 1 to 5 where 1 is rare and 5 is constant}
#'   \item{freq}{The probability/frequency of occurrence, these are related to the constancy where 1 = 0.1, 2 = 0.3, 3 = 0.5, 4 = 0.7, 5 = 0.9}
#' }
#'
"NVC_communities"
